'use strict'

const ukLocalAuthorities = [
    {value: 'Unknown', label: 'Unknown'},
    {value: 'Bournemouth, Christchurch and Poole Council', label: 'Bournemouth, Christchurch and Poole Council'},
    {value: 'Dorset Council', label: 'Dorset Council'},
    {value: 'Somerset West and Taunton Council', label: 'Somerset West and Taunton Council'},
    {value: 'West Suffolk Council', label: 'West Suffolk Council'},
    {value: 'East Suffolk Council', label: 'East Suffolk Council'},
    {value: 'Weymouth and Portland Borough Council', label: 'Weymouth and Portland Borough Council'},
    {value: 'West Dorset District Council', label: 'West Dorset District Council'},
    {value: 'Purbeck District Council', label: 'Purbeck District Council'},
    {value: 'North Dorset District Council', label: 'North Dorset District Council'},
    {value: 'East Dorset District Council', label: 'East Dorset District Council'},
    {value: 'Dorset County Council', label: 'Dorset County Council'},
    {value: 'Christchurch Borough Council', label: 'Christchurch Borough Council'},
    {value: 'Borough of Poole', label: 'Borough of Poole'},
    {value: 'Bournemouth Borough Council', label: 'Bournemouth Borough Council'},
    {value: 'St Edmundsbury Borough Council', label: 'St Edmundsbury Borough Council'},
    {value: 'Forest Heath District Council', label: 'Forest Heath District Council'},
    {value: 'West Somerset District Council', label: 'West Somerset District Council'},
    {value: 'Taunton Deane Borough Council', label: 'Taunton Deane Borough Council'},
    {value: 'Waveney District Council', label: 'Waveney District Council'},
    {value: 'Suffolk Coastal District Council', label: 'Suffolk Coastal District Council'},
    {value: 'Tees Valley Combined Authority', label: 'Tees Valley Combined Authority'},
    {value: 'Cambridgeshire and Peterborough Combined Authority', label: 'Cambridgeshire and Peterborough Combined Authority'},
    {value: 'West Midlands Combined Authority', label: 'West Midlands Combined Authority'},
    {value: 'Greater Manchester Combined Authority', label: 'Greater Manchester Combined Authority'},
    {value: 'West of England Combined Authority', label: 'West of England Combined Authority'},
    {value: 'Sheffield City Region', label: 'Sheffield City Region'},
    {value: 'Liverpool City Region', label: 'Liverpool City Region'},
    {value: 'Folkestone and Hythe Council', label: 'Folkestone and Hythe Council'},
    {value: 'Birmingham City Council', label: 'Birmingham City Council'},
    {value: 'Borough Council of King\'s Lynn and West Norfolk', label: 'Borough Council of King\'s Lynn and West Norfolk'},
    {value: 'Greater London Authority', label: 'Greater London Authority'},
    {value: 'City of London Corporation', label: 'City of London Corporation'},
    {value: 'Worthing Borough Council', label: 'Worthing Borough Council'},
    {value: 'Mid Sussex District Council', label: 'Mid Sussex District Council'},
    {value: 'Horsham District Council', label: 'Horsham District Council'},
    {value: 'Crawley Borough Council', label: 'Crawley Borough Council'},
    {value: 'Chichester District Council', label: 'Chichester District Council'},
    {value: 'Arun District Council', label: 'Arun District Council'},
    {value: 'Adur District Council', label: 'Adur District Council'},
    {value: 'West Sussex County Council', label: 'West Sussex County Council'},
    {value: 'Wyre Forest District Council', label: 'Wyre Forest District Council'},
    {value: 'Wychavon District Council', label: 'Wychavon District Council'},
    {value: 'Worcester City Council', label: 'Worcester City Council'},
    {value: 'Redditch Borough Council', label: 'Redditch Borough Council'},
    {value: 'Malvern Hills District Council', label: 'Malvern Hills District Council'},
    {value: 'Bromsgrove District Council', label: 'Bromsgrove District Council'},
    {value: 'Worcestershire County Council', label: 'Worcestershire County Council'},
    {value: 'Warwick District Council', label: 'Warwick District Council'},
    {value: 'Stratford-on-Avon District Council', label: 'Stratford-on-Avon District Council'},
    {value: 'Rugby Borough Council', label: 'Rugby Borough Council'},
    {value: 'Nuneaton and Bedworth Borough Council', label: 'Nuneaton and Bedworth Borough Council'},
    {value: 'North Warwickshire Borough Council', label: 'North Warwickshire Borough Council'},
    {value: 'Warwickshire County Council', label: 'Warwickshire County Council'},
    {value: 'Tamworth Borough Council', label: 'Tamworth Borough Council'},
    {value: 'Staffordshire Moorlands District Council', label: 'Staffordshire Moorlands District Council'},
    {value: 'Stafford Borough Council', label: 'Stafford Borough Council'},
    {value: 'South Staffordshire Council', label: 'South Staffordshire Council'},
    {value: 'Newcastle-under-Lyme Borough Council', label: 'Newcastle-under-Lyme Borough Council'},
    {value: 'Lichfield District Council', label: 'Lichfield District Council'},
    {value: 'East Staffordshire Borough Council', label: 'East Staffordshire Borough Council'},
    {value: 'Cannock Chase District Council', label: 'Cannock Chase District Council'},
    {value: 'Staffordshire County Council', label: 'Staffordshire County Council'},
    {value: 'Woking Borough Council', label: 'Woking Borough Council'},
    {value: 'Waverley Borough Council', label: 'Waverley Borough Council'},
    {value: 'Tandridge District Council', label: 'Tandridge District Council'},
    {value: 'Surrey Heath Borough Council', label: 'Surrey Heath Borough Council'},
    {value: 'Spelthorne Borough Council', label: 'Spelthorne Borough Council'},
    {value: 'Runnymede Borough Council', label: 'Runnymede Borough Council'},
    {value: 'Reigate and Banstead Borough Council', label: 'Reigate and Banstead Borough Council'},
    {value: 'Mole Valley District Council', label: 'Mole Valley District Council'},
    {value: 'Guildford Borough Council', label: 'Guildford Borough Council'},
    {value: 'Epsom and Ewell Borough Council', label: 'Epsom and Ewell Borough Council'},
    {value: 'Elmbridge Borough Council', label: 'Elmbridge Borough Council'},
    {value: 'Surrey County Council', label: 'Surrey County Council'},
    {value: 'South Somerset District Council', label: 'South Somerset District Council'},
    {value: 'Sedgemoor District Council', label: 'Sedgemoor District Council'},
    {value: 'Mendip District Council', label: 'Mendip District Council'},
    {value: 'Somerset County Council', label: 'Somerset County Council'},
    {value: 'Mid Suffolk District Council', label: 'Mid Suffolk District Council'},
    {value: 'Ipswich Borough Council', label: 'Ipswich Borough Council'},
    {value: 'Babergh District Council', label: 'Babergh District Council'},
    {value: 'Suffolk County Council', label: 'Suffolk County Council'},
    {value: 'West Oxfordshire District Council', label: 'West Oxfordshire District Council'},
    {value: 'Vale of White Horse District Council', label: 'Vale of White Horse District Council'},
    {value: 'South Oxfordshire District Council', label: 'South Oxfordshire District Council'},
    {value: 'Oxford City Council', label: 'Oxford City Council'},
    {value: 'Cherwell District Council', label: 'Cherwell District Council'},
    {value: 'Oxfordshire County Council', label: 'Oxfordshire County Council'},
    {value: 'Selby District Council', label: 'Selby District Council'},
    {value: 'Scarborough Borough Council', label: 'Scarborough Borough Council'},
    {value: 'Ryedale District Council', label: 'Ryedale District Council'},
    {value: 'Richmondshire District Council', label: 'Richmondshire District Council'},
    {value: 'Harrogate Borough Council', label: 'Harrogate Borough Council'},
    {value: 'Hambleton District Council', label: 'Hambleton District Council'},
    {value: 'Craven District Council', label: 'Craven District Council'},
    {value: 'North Yorkshire County Council', label: 'North Yorkshire County Council'},
    {value: 'Rushcliffe Borough Council', label: 'Rushcliffe Borough Council'},
    {value: 'Newark and Sherwood District Council', label: 'Newark and Sherwood District Council'},
    {value: 'Mansfield District Council', label: 'Mansfield District Council'},
    {value: 'Gedling Borough Council', label: 'Gedling Borough Council'},
    {value: 'Broxtowe Borough Council', label: 'Broxtowe Borough Council'},
    {value: 'Bassetlaw District Council', label: 'Bassetlaw District Council'},
    {value: 'Ashfield District Council', label: 'Ashfield District Council'},
    {value: 'Nottinghamshire County Council', label: 'Nottinghamshire County Council'},
    {value: 'Wellingborough Borough Council', label: 'Wellingborough Borough Council'},
    {value: 'South Northamptonshire Council', label: 'South Northamptonshire Council'},
    {value: 'Northampton Borough Council', label: 'Northampton Borough Council'},
    {value: 'Kettering Borough Council', label: 'Kettering Borough Council'},
    {value: 'East Northamptonshire Council', label: 'East Northamptonshire Council'},
    {value: 'Daventry District Council', label: 'Daventry District Council'},
    {value: 'Corby Borough Council', label: 'Corby Borough Council'},
    {value: 'Northamptonshire County Council', label: 'Northamptonshire County Council'},
    {value: 'South Norfolk District Council', label: 'South Norfolk District Council'},
    {value: 'Norwich City Council', label: 'Norwich City Council'},
    {value: 'North Norfolk District Council', label: 'North Norfolk District Council'},
    {value: 'Great Yarmouth Borough Council', label: 'Great Yarmouth Borough Council'},
    {value: 'Broadland District Council', label: 'Broadland District Council'},
    {value: 'Breckland District Council', label: 'Breckland District Council'},
    {value: 'Norfolk County Council', label: 'Norfolk County Council'},
    {value: 'West Lindsey District Council', label: 'West Lindsey District Council'},
    {value: 'South Kesteven District Council', label: 'South Kesteven District Council'},
    {value: 'South Holland District Council', label: 'South Holland District Council'},
    {value: 'North Kesteven District Council', label: 'North Kesteven District Council'},
    {value: 'City of Lincoln Council', label: 'City of Lincoln Council'},
    {value: 'East Lindsey District Council', label: 'East Lindsey District Council'},
    {value: 'Boston Borough Council', label: 'Boston Borough Council'},
    {value: 'Lincolnshire County Council', label: 'Lincolnshire County Council'},
    {value: 'Oadby and Wigston Borough Council', label: 'Oadby and Wigston Borough Council'},
    {value: 'North West Leicestershire District Council', label: 'North West Leicestershire District Council'},
    {value: 'Melton Borough Council', label: 'Melton Borough Council'},
    {value: 'Hinckley and Bosworth Borough Council', label: 'Hinckley and Bosworth Borough Council'},
    {value: 'Harborough District Council', label: 'Harborough District Council'},
    {value: 'Charnwood Borough Council', label: 'Charnwood Borough Council'},
    {value: 'Blaby District Council', label: 'Blaby District Council'},
    {value: 'Leicestershire County Council', label: 'Leicestershire County Council'},
    {value: 'Wyre Borough Council', label: 'Wyre Borough Council'},
    {value: 'West Lancashire Borough Council', label: 'West Lancashire Borough Council'},
    {value: 'South Ribble Borough Council', label: 'South Ribble Borough Council'},
    {value: 'Rossendale Borough Council', label: 'Rossendale Borough Council'},
    {value: 'Ribble Valley Borough Council', label: 'Ribble Valley Borough Council'},
    {value: 'Preston City Council', label: 'Preston City Council'},
    {value: 'Pendle Borough Council', label: 'Pendle Borough Council'},
    {value: 'Lancaster City Council', label: 'Lancaster City Council'},
    {value: 'Hyndburn Borough Council', label: 'Hyndburn Borough Council'},
    {value: 'Fylde Borough Council', label: 'Fylde Borough Council'},
    {value: 'Chorley Borough Council', label: 'Chorley Borough Council'},
    {value: 'Burnley Borough Council', label: 'Burnley Borough Council'},
    {value: 'Lancashire County Council', label: 'Lancashire County Council'},
    {value: 'Tunbridge Wells Borough Council', label: 'Tunbridge Wells Borough Council'},
    {value: 'Tonbridge and Malling Borough Council', label: 'Tonbridge and Malling Borough Council'},
    {value: 'Thanet District Council', label: 'Thanet District Council'},
    {value: 'Swale Borough Council', label: 'Swale Borough Council'},
    {value: 'Sevenoaks District Council', label: 'Sevenoaks District Council'},
    {value: 'Maidstone Borough Council', label: 'Maidstone Borough Council'},
    {value: 'Gravesham Borough Council', label: 'Gravesham Borough Council'},
    {value: 'Dover District Council', label: 'Dover District Council'},
    {value: 'Dartford Borough Council', label: 'Dartford Borough Council'},
    {value: 'Canterbury City Council', label: 'Canterbury City Council'},
    {value: 'Ashford Borough Council', label: 'Ashford Borough Council'},
    {value: 'Kent County Council', label: 'Kent County Council'},
    {value: 'Welwyn Hatfield Borough Council', label: 'Welwyn Hatfield Borough Council'},
    {value: 'Watford Borough Council', label: 'Watford Borough Council'},
    {value: 'Three Rivers District Council', label: 'Three Rivers District Council'},
    {value: 'Stevenage Borough Council', label: 'Stevenage Borough Council'},
    {value: 'St Albans City and District Council', label: 'St Albans City and District Council'},
    {value: 'North Hertfordshire District Council', label: 'North Hertfordshire District Council'},
    {value: 'Hertsmere Borough Council', label: 'Hertsmere Borough Council'},
    {value: 'East Hertfordshire District Council', label: 'East Hertfordshire District Council'},
    {value: 'Dacorum Borough Council', label: 'Dacorum Borough Council'},
    {value: 'Broxbourne Borough Council', label: 'Broxbourne Borough Council'},
    {value: 'Hertfordshire County Council', label: 'Hertfordshire County Council'},
    {value: 'Winchester City Council', label: 'Winchester City Council'},
    {value: 'Test Valley Borough Council', label: 'Test Valley Borough Council'},
    {value: 'Rushmoor Borough Council', label: 'Rushmoor Borough Council'},
    {value: 'New Forest District Council', label: 'New Forest District Council'},
    {value: 'Havant Borough Council', label: 'Havant Borough Council'},
    {value: 'Hart District Council', label: 'Hart District Council'},
    {value: 'Gosport Borough Council', label: 'Gosport Borough Council'},
    {value: 'Fareham Borough Council', label: 'Fareham Borough Council'},
    {value: 'Eastleigh Borough Council', label: 'Eastleigh Borough Council'},
    {value: 'East Hampshire District Council', label: 'East Hampshire District Council'},
    {value: 'Basingstoke and Deane Borough Council', label: 'Basingstoke and Deane Borough Council'},
    {value: 'Hampshire County Council', label: 'Hampshire County Council'},
    {value: 'Tewkesbury Borough Council', label: 'Tewkesbury Borough Council'},
    {value: 'Stroud District Council', label: 'Stroud District Council'},
    {value: 'Gloucester City Council', label: 'Gloucester City Council'},
    {value: 'Forest of Dean District Council', label: 'Forest of Dean District Council'},
    {value: 'Cotswold District Council', label: 'Cotswold District Council'},
    {value: 'Cheltenham Borough Council', label: 'Cheltenham Borough Council'},
    {value: 'Gloucestershire County Council', label: 'Gloucestershire County Council'},
    {value: 'City of Westminster', label: 'City of Westminster'},
    {value: 'London Borough of Wandsworth', label: 'London Borough of Wandsworth'},
    {value: 'London Borough of Waltham Forest', label: 'London Borough of Waltham Forest'},
    {value: 'London Borough of Tower Hamlets', label: 'London Borough of Tower Hamlets'},
    {value: 'London Borough of Southwark', label: 'London Borough of Southwark'},
    {value: 'London Borough of Sutton', label: 'London Borough of Sutton'},
    {value: 'London Borough of Richmond upon Thames', label: 'London Borough of Richmond upon Thames'},
    {value: 'London Borough of Redbridge', label: 'London Borough of Redbridge'},
    {value: 'London Borough of Newham', label: 'London Borough of Newham'},
    {value: 'London Borough of Merton', label: 'London Borough of Merton'},
    {value: 'London Borough of Lewisham', label: 'London Borough of Lewisham'},
    {value: 'London Borough of Lambeth', label: 'London Borough of Lambeth'},
    {value: 'Royal Borough of Kingston upon Thames', label: 'Royal Borough of Kingston upon Thames'},
    {value: 'Royal Borough of Kensington and Chelsea', label: 'Royal Borough of Kensington and Chelsea'},
    {value: 'London Borough of Islington', label: 'London Borough of Islington'},
    {value: 'London Borough of Haringey', label: 'London Borough of Haringey'},
    {value: 'London Borough of Harrow', label: 'London Borough of Harrow'},
    {value: 'London Borough of Hounslow', label: 'London Borough of Hounslow'},
    {value: 'London Borough of Hammersmith & Fulham', label: 'London Borough of Hammersmith & Fulham'},
    {value: 'London Borough of Hillingdon', label: 'London Borough of Hillingdon'},
    {value: 'London Borough of Hackney', label: 'London Borough of Hackney'},
    {value: 'London Borough of Havering', label: 'London Borough of Havering'},
    {value: 'Royal Borough of Greenwich', label: 'Royal Borough of Greenwich'},
    {value: 'London Borough of Enfield', label: 'London Borough of Enfield'},
    {value: 'London Borough of Ealing', label: 'London Borough of Ealing'},
    {value: 'London Borough of Croydon', label: 'London Borough of Croydon'},
    {value: 'London Borough of Camden', label: 'London Borough of Camden'},
    {value: 'London Borough of Bromley', label: 'London Borough of Bromley'},
    {value: 'London Borough of Barnet', label: 'London Borough of Barnet'},
    {value: 'London Borough of Bexley', label: 'London Borough of Bexley'},
    {value: 'London Borough of Brent', label: 'London Borough of Brent'},
    {value: 'London Borough of Barking and Dagenham', label: 'London Borough of Barking and Dagenham'},
    {value: 'Wealden District Council', label: 'Wealden District Council'},
    {value: 'Rother District Council', label: 'Rother District Council'},
    {value: 'Lewes District Council', label: 'Lewes District Council'},
    {value: 'Hastings Borough Council', label: 'Hastings Borough Council'},
    {value: 'Eastbourne Borough Council', label: 'Eastbourne Borough Council'},
    {value: 'East Sussex County Council', label: 'East Sussex County Council'},
    {value: 'Uttlesford District Council', label: 'Uttlesford District Council'},
    {value: 'Tendring District Council', label: 'Tendring District Council'},
    {value: 'Rochford District Council', label: 'Rochford District Council'},
    {value: 'Maldon District Council', label: 'Maldon District Council'},
    {value: 'Harlow District Council', label: 'Harlow District Council'},
    {value: 'Epping Forest District Council', label: 'Epping Forest District Council'},
    {value: 'Colchester Borough Council', label: 'Colchester Borough Council'},
    {value: 'Chelmsford City Council', label: 'Chelmsford City Council'},
    {value: 'Castle Point Borough Council', label: 'Castle Point Borough Council'},
    {value: 'Brentwood Borough Council', label: 'Brentwood Borough Council'},
    {value: 'Braintree District Council', label: 'Braintree District Council'},
    {value: 'Basildon Borough Council', label: 'Basildon Borough Council'},
    {value: 'Essex County Council', label: 'Essex County Council'},
    {value: 'West Devon Borough Council', label: 'West Devon Borough Council'},
    {value: 'Torridge District Council', label: 'Torridge District Council'},
    {value: 'Teignbridge District Council', label: 'Teignbridge District Council'},
    {value: 'South Hams District Council', label: 'South Hams District Council'},
    {value: 'North Devon District Council', label: 'North Devon District Council'},
    {value: 'Mid Devon District Council', label: 'Mid Devon District Council'},
    {value: 'Exeter City Council', label: 'Exeter City Council'},
    {value: 'East Devon District Council', label: 'East Devon District Council'},
    {value: 'Devon County Council', label: 'Devon County Council'},
    {value: 'South Derbyshire District Council', label: 'South Derbyshire District Council'},
    {value: 'North East Derbyshire District Council', label: 'North East Derbyshire District Council'},
    {value: 'High Peak Borough Council', label: 'High Peak Borough Council'},
    {value: 'Erewash Borough Council', label: 'Erewash Borough Council'},
    {value: 'Derbyshire Dales District Council', label: 'Derbyshire Dales District Council'},
    {value: 'Chesterfield Borough Council', label: 'Chesterfield Borough Council'},
    {value: 'Bolsover District Council', label: 'Bolsover District Council'},
    {value: 'Amber Valley Borough Council', label: 'Amber Valley Borough Council'},
    {value: 'Derbyshire County Council', label: 'Derbyshire County Council'},
    {value: 'Derby City Council', label: 'Derby City Council'},
    {value: 'South Lakeland District Council', label: 'South Lakeland District Council'},
    {value: 'Eden District Council', label: 'Eden District Council'},
    {value: 'Copeland Borough Council', label: 'Copeland Borough Council'},
    {value: 'Carlisle City Council', label: 'Carlisle City Council'},
    {value: 'Barrow-in-Furness Borough Council', label: 'Barrow-in-Furness Borough Council'},
    {value: 'Allerdale Borough Council', label: 'Allerdale Borough Council'},
    {value: 'Cumbria County Council', label: 'Cumbria County Council'},
    {value: 'South Cambridgeshire District Council', label: 'South Cambridgeshire District Council'},
    {value: 'Huntingdonshire District Council', label: 'Huntingdonshire District Council'},
    {value: 'Fenland District Council', label: 'Fenland District Council'},
    {value: 'East Cambridgeshire District Council', label: 'East Cambridgeshire District Council'},
    {value: 'Cambridge City Council', label: 'Cambridge City Council'},
    {value: 'Cambridgeshire County Council', label: 'Cambridgeshire County Council'},
    {value: 'Wycombe District Council', label: 'Wycombe District Council'},
    {value: 'South Bucks District Council', label: 'South Bucks District Council'},
    {value: 'Chiltern District Council', label: 'Chiltern District Council'},
    {value: 'Aylesbury Vale District Council', label: 'Aylesbury Vale District Council'},
    {value: 'Buckinghamshire County Council', label: 'Buckinghamshire County Council'},
    {value: 'City of York Council', label: 'City of York Council'},
    {value: 'Warrington Borough Council', label: 'Warrington Borough Council'},
    {value: 'Wirral Borough Council', label: 'Wirral Borough Council'},
    {value: 'Wokingham Borough Council', label: 'Wokingham Borough Council'},
    {value: 'Royal Borough of Windsor and Maidenhead', label: 'Royal Borough of Windsor and Maidenhead'},
    {value: 'City of Wolverhampton Council', label: 'City of Wolverhampton Council'},
    {value: 'Walsall Metropolitan Borough Council', label: 'Walsall Metropolitan Borough Council'},
    {value: 'Wakefield Metropolitan District Council', label: 'Wakefield Metropolitan District Council'},
    {value: 'Wiltshire Council', label: 'Wiltshire Council'},
    {value: 'Wigan Metropolitan Borough Council', label: 'Wigan Metropolitan Borough Council'},
    {value: 'West Berkshire Council', label: 'West Berkshire Council'},
    {value: 'Trafford Metropolitan Borough Council', label: 'Trafford Metropolitan Borough Council'},
    {value: 'Torbay Council', label: 'Torbay Council'},
    {value: 'Thurrock Council', label: 'Thurrock Council'},
    {value: 'Telford & Wrekin Council', label: 'Telford & Wrekin Council'},
    {value: 'Tameside Metropolitan Borough Council', label: 'Tameside Metropolitan Borough Council'},
    {value: 'Swindon Borough Council', label: 'Swindon Borough Council'},
    {value: 'South Tyneside Council', label: 'South Tyneside Council'},
    {value: 'Stockton-on-Tees Borough Council', label: 'Stockton-on-Tees Borough Council'},
    {value: 'Southampton City Council', label: 'Southampton City Council'},
    {value: 'Stoke-on-Trent City Council', label: 'Stoke-on-Trent City Council'},
    {value: 'Southend-on-Sea Borough Council', label: 'Southend-on-Sea Borough Council'},
    {value: 'Solihull Metropolitan Borough Council', label: 'Solihull Metropolitan Borough Council'},
    {value: 'Sunderland City Council', label: 'Sunderland City Council'},
    {value: 'Slough Borough Council', label: 'Slough Borough Council'},
    {value: 'Salford City Council', label: 'Salford City Council'},
    {value: 'Stockport Metropolitan Borough Council', label: 'Stockport Metropolitan Borough Council'},
    {value: 'Shropshire Council', label: 'Shropshire Council'},
    {value: 'St Helens Council', label: 'St Helens Council'},
    {value: 'Sheffield City Council', label: 'Sheffield City Council'},
    {value: 'South Gloucestershire Council', label: 'South Gloucestershire Council'},
    {value: 'Sefton Metropolitan Borough Council', label: 'Sefton Metropolitan Borough Council'},
    {value: 'Sandwell Metropolitan Borough Council', label: 'Sandwell Metropolitan Borough Council'},
    {value: 'Rutland County Council', label: 'Rutland County Council'},
    {value: 'Rotherham Metropolitan Borough Council', label: 'Rotherham Metropolitan Borough Council'},
    {value: 'Reading Borough Council', label: 'Reading Borough Council'},
    {value: 'Rochdale Metropolitan Borough Council', label: 'Rochdale Metropolitan Borough Council'},
    {value: 'Redcar and Cleveland Borough Council', label: 'Redcar and Cleveland Borough Council'},
    {value: 'Peterborough City Council', label: 'Peterborough City Council'},
    {value: 'Portsmouth City Council', label: 'Portsmouth City Council'},
    {value: 'Plymouth City Council', label: 'Plymouth City Council'},
    {value: 'Oldham Metropolitan Borough Council', label: 'Oldham Metropolitan Borough Council'},
    {value: 'North Tyneside Council', label: 'North Tyneside Council'},
    {value: 'North Somerset Council', label: 'North Somerset Council'},
    {value: 'North Lincolnshire Council', label: 'North Lincolnshire Council'},
    {value: 'Nottingham City Council', label: 'Nottingham City Council'},
    {value: 'Newcastle City Council', label: 'Newcastle City Council'},
    {value: 'North East Lincolnshire Council', label: 'North East Lincolnshire Council'},
    {value: 'Northumberland County Council', label: 'Northumberland County Council'},
    {value: 'Milton Keynes Council', label: 'Milton Keynes Council'},
    {value: 'Medway Council', label: 'Medway Council'},
    {value: 'Middlesbrough Borough Council', label: 'Middlesbrough Borough Council'},
    {value: 'Manchester City Council', label: 'Manchester City Council'},
    {value: 'Luton Borough Council', label: 'Luton Borough Council'},
    {value: 'Liverpool City Council', label: 'Liverpool City Council'},
    {value: 'Leeds City Council', label: 'Leeds City Council'},
    {value: 'Leicester City Council', label: 'Leicester City Council'},
    {value: 'Knowsley Metropolitan Borough Council', label: 'Knowsley Metropolitan Borough Council'},
    {value: 'Kirklees Council', label: 'Kirklees Council'},
    {value: 'Hull City Council', label: 'Hull City Council'},
    {value: 'Isle of Wight Council', label: 'Isle of Wight Council'},
    {value: 'Council of the Isles of Scilly', label: 'Council of the Isles of Scilly'},
    {value: 'Hartlepool Borough Council', label: 'Hartlepool Borough Council'},
    {value: 'Herefordshire Council', label: 'Herefordshire Council'},
    {value: 'Halton Borough Council', label: 'Halton Borough Council'},
    {value: 'Gateshead Metropolitan Borough Council', label: 'Gateshead Metropolitan Borough Council'},
    {value: 'East Riding of Yorkshire Council', label: 'East Riding of Yorkshire Council'},
    {value: 'Durham County Council', label: 'Durham County Council'},
    {value: 'Dudley Metropolitan Borough Council', label: 'Dudley Metropolitan Borough Council'},
    {value: 'Doncaster Metropolitan Borough Council', label: 'Doncaster Metropolitan Borough Council'},
    {value: 'Darlington Borough Council', label: 'Darlington Borough Council'},
    {value: 'Coventry City Council', label: 'Coventry City Council'},
    {value: 'Cornwall Council', label: 'Cornwall Council'},
    {value: 'Calderdale Metropolitan Borough Council', label: 'Calderdale Metropolitan Borough Council'},
    {value: 'Cheshire West and Chester Council', label: 'Cheshire West and Chester Council'},
    {value: 'Cheshire East Council', label: 'Cheshire East Council'},
    {value: 'Central Bedfordshire Council', label: 'Central Bedfordshire Council'},
    {value: 'Bury Metropolitan Borough Council', label: 'Bury Metropolitan Borough Council'},
    {value: 'Bristol City Council', label: 'Bristol City Council'},
    {value: 'City of Bradford Metropolitan District Council', label: 'City of Bradford Metropolitan District Council'},
    {value: 'Bracknell Forest Council', label: 'Bracknell Forest Council'},
    {value: 'Blackpool Borough Council', label: 'Blackpool Borough Council'},
    {value: 'Bolton Metropolitan Borough Council', label: 'Bolton Metropolitan Borough Council'},
    {value: 'Barnsley Metropolitan Borough Council', label: 'Barnsley Metropolitan Borough Council'},
    {value: 'Brighton and Hove City Council', label: 'Brighton and Hove City Council'},
    {value: 'Bedford Borough Council', label: 'Bedford Borough Council'},
    {value: 'Blackburn with Darwen Borough Council', label: 'Blackburn with Darwen Borough Council'},
    {value: 'Bath and North East Somerset Council', label: 'Bath and North East Somerset Council'},
    {value: 'Na h-Eileanan an Iar', label: 'Na h-Eileanan an Iar'},
    {value: 'Shetland Islands', label: 'Shetland Islands'},
    {value: 'West Lothian', label: 'West Lothian'},
    {value: 'West Dunbartonshire', label: 'West Dunbartonshire'},
    {value: 'Stirling', label: 'Stirling'},
    {value: 'South Lanarkshire', label: 'South Lanarkshire'},
    {value: 'Scottish Borders', label: 'Scottish Borders'},
    {value: 'South Ayrshire', label: 'South Ayrshire'},
    {value: 'Renfrewshire', label: 'Renfrewshire'},
    {value: 'Perth and Kinross', label: 'Perth and Kinross'},
    {value: 'Orkney Islands', label: 'Orkney Islands'},
    {value: 'North Lanarkshire', label: 'North Lanarkshire'},
    {value: 'North Ayrshire', label: 'North Ayrshire'},
    {value: 'Moray', label: 'Moray'},
    {value: 'Midlothian', label: 'Midlothian'},
    {value: 'Inverclyde', label: 'Inverclyde'},
    {value: 'Highland', label: 'Highland'},
    {value: 'Glasgow City', label: 'Glasgow City'},
    {value: 'Fife', label: 'Fife'},
    {value: 'Falkirk', label: 'Falkirk'},
    {value: 'East Renfrewshire', label: 'East Renfrewshire'},
    {value: 'East Lothian', label: 'East Lothian'},
    {value: 'East Dunbartonshire', label: 'East Dunbartonshire'},
    {value: 'Edinburgh', label: 'Edinburgh'},
    {value: 'East Ayrshire', label: 'East Ayrshire'},
    {value: 'Dundee City', label: 'Dundee City'},
    {value: 'Dumfries and Galloway', label: 'Dumfries and Galloway'},
    {value: 'Clackmannanshire', label: 'Clackmannanshire'},
    {value: 'Angus', label: 'Angus'},
    {value: 'Argyll and Bute', label: 'Argyll and Bute'},
    {value: 'Aberdeen City', label: 'Aberdeen City'},
    {value: 'Aberdeenshire', label: 'Aberdeenshire'},
    {value: 'Rhondda Cynon Taf County Borough Council', label: 'Rhondda Cynon Taf County Borough Council'},
    {value: 'Wrexham County Borough Council', label: 'Wrexham County Borough Council'},
    {value: 'Vale of Glamorgan Council', label: 'Vale of Glamorgan Council'},
    {value: 'Torfaen County Borough Council', label: 'Torfaen County Borough Council'},
    {value: 'City and County of Swansea Council', label: 'City and County of Swansea Council'},
    {value: 'Powys County Council', label: 'Powys County Council'},
    {value: 'Pembrokeshire County Council', label: 'Pembrokeshire County Council'},
    {value: 'Newport City Council', label: 'Newport City Council'},
    {value: 'Neath Port Talbot County Borough Council', label: 'Neath Port Talbot County Borough Council'},
    {value: 'Merthyr Tydfil County Borough Council', label: 'Merthyr Tydfil County Borough Council'},
    {value: 'Monmouthshire County Council', label: 'Monmouthshire County Council'},
    {value: 'Gwynedd Council', label: 'Gwynedd Council'},
    {value: 'Flintshire County Council', label: 'Flintshire County Council'},
    {value: 'Denbighshire County Council', label: 'Denbighshire County Council'},
    {value: 'Conwy County Borough Council', label: 'Conwy County Borough Council'},
    {value: 'City of Cardiff Council', label: 'City of Cardiff Council'},
    {value: 'Carmarthenshire County Council', label: 'Carmarthenshire County Council'},
    {value: 'Ceredigion County Council', label: 'Ceredigion County Council'},
    {value: 'Caerphilly County Borough Council', label: 'Caerphilly County Borough Council'},
    {value: 'Blaenau Gwent County Borough Council', label: 'Blaenau Gwent County Borough Council'},
    {value: 'Bridgend County Borough Council', label: 'Bridgend County Borough Council'},
    {value: 'Isle of Anglesey County Council', label: 'Isle of Anglesey County Council'},
    {value: 'Armagh City, Banbridge and Craigavon Borough Council', label: 'Armagh City, Banbridge and Craigavon Borough Council'},
    {value: 'Ards and North Down Borough Council', label: 'Ards and North Down Borough Council'},
    {value: 'Antrim & Newtownabbey Borough Council', label: 'Antrim & Newtownabbey Borough Council'},
    {value: 'Belfast City Council', label: 'Belfast City Council'},
    {value: 'Causeway Coast and Glens Borough Council', label: 'Causeway Coast and Glens Borough Council'},
    {value: 'Derry City and Strabane District Council', label: 'Derry City and Strabane District Council'},
    {value: 'Fermanagh and Omagh District Council', label: 'Fermanagh and Omagh District Council'},
    {value: 'Lisburn & Castlereagh City Council', label: 'Lisburn & Castlereagh City Council'},
    {value: 'Mid & East Antrim Borough Council', label: 'Mid & East Antrim Borough Council'},
    {value: 'Mid Ulster District Council', label: 'Mid Ulster District Council'},
    {value: 'Newry, Mourne and Down District Council', label: 'Newry, Mourne and Down District Council'},
    {value: 'Derry City Council', label: 'Derry City Council'},
    {value: 'Limavady Borough Council', label: 'Limavady Borough Council'},
    {value: 'Coleraine Borough Council', label: 'Coleraine Borough Council'},
    {value: 'Ballymoney Borough Council', label: 'Ballymoney Borough Council'},
    {value: 'Moyle District Council', label: 'Moyle District Council'},
    {value: 'Larne Borough Council', label: 'Larne Borough Council'},
    {value: 'Ballymena Borough Council', label: 'Ballymena Borough Council'},
    {value: 'Magherafelt District Council', label: 'Magherafelt District Council'},
    {value: 'Cookstown District Council', label: 'Cookstown District Council'},
    {value: 'Strabane District Council', label: 'Strabane District Council'},
    {value: 'Omagh District Council', label: 'Omagh District Council'},
    {value: 'Fermanagh District Council', label: 'Fermanagh District Council'},
    {value: 'Dungannon and South Tyrone Borough Council', label: 'Dungannon and South Tyrone Borough Council'},
    {value: 'Craigavon Borough Council', label: 'Craigavon Borough Council'},
    {value: 'Armagh City and District Council', label: 'Armagh City and District Council'},
    {value: 'Newry and Mourne District Council', label: 'Newry and Mourne District Council'},
    {value: 'Banbridge District Council', label: 'Banbridge District Council'},
    {value: 'Down District Council', label: 'Down District Council'},
    {value: 'Lisburn City Council', label: 'Lisburn City Council'},
    {value: 'Antrim Borough Council', label: 'Antrim Borough Council'},
    {value: 'Newtownabbey Borough Council', label: 'Newtownabbey Borough Council'},
    {value: 'Carrickfergus Borough Council', label: 'Carrickfergus Borough Council'},
    {value: 'North Down Borough Council', label: 'North Down Borough Council'},
    {value: 'Ards Borough Council', label: 'Ards Borough Council'},
    {value: 'Castlereagh Borough Council', label: 'Castlereagh Borough Council'},
    {value: 'Comhairle nan Eilean Siar', label: 'Comhairle nan Eilean Siar'},
    {value: 'Shetland Islands Council', label: 'Shetland Islands Council'},
    {value: 'The West Lothian Council', label: 'The West Lothian Council'},
    {value: 'The West Dunbartonshire Council', label: 'The West Dunbartonshire Council'},
    {value: 'The Stirling Council', label: 'The Stirling Council'},
    {value: 'The South Lanarkshire Council', label: 'The South Lanarkshire Council'},
    {value: 'The Scottish Borders Council', label: 'The Scottish Borders Council'},
    {value: 'The South Ayrshire Council', label: 'The South Ayrshire Council'},
    {value: 'The Renfrewshire Council', label: 'The Renfrewshire Council'},
    {value: 'The Perth and Kinross Council', label: 'The Perth and Kinross Council'},
    {value: 'Orkney Islands Council', label: 'Orkney Islands Council'},
    {value: 'The North Lanarkshire Council', label: 'The North Lanarkshire Council'},
    {value: 'The North Ayrshire Council', label: 'The North Ayrshire Council'},
    {value: 'The Moray Council', label: 'The Moray Council'},
    {value: 'The Midlothian Council', label: 'The Midlothian Council'},
    {value: 'The Inverclyde Council', label: 'The Inverclyde Council'},
    {value: 'The Highland Council', label: 'The Highland Council'},
    {value: 'The Glasgow City Council', label: 'The Glasgow City Council'},
    {value: 'The Fife Council', label: 'The Fife Council'},
    {value: 'The Falkirk Council', label: 'The Falkirk Council'},
    {value: 'The East Renfrewshire Council', label: 'The East Renfrewshire Council'},
    {value: 'The East Lothian Council', label: 'The East Lothian Council'},
    {value: 'The East Dunbartonshire Council', label: 'The East Dunbartonshire Council'},
    {value: 'The City of Edinburgh Council', label: 'The City of Edinburgh Council'},
    {value: 'The East Ayrshire Council', label: 'The East Ayrshire Council'},
    {value: 'The Dundee City Council', label: 'The Dundee City Council'},
    {value: 'The Dumfries and Galloway Council', label: 'The Dumfries and Galloway Council'},
    {value: 'The Clackmannanshire Council', label: 'The Clackmannanshire Council'},
    {value: 'The Angus Council', label: 'The Angus Council'},
    {value: 'The Argyll and Bute Council', label: 'The Argyll and Bute Council'},
    {value: 'The Aberdeen City Council', label: 'The Aberdeen City Council'},
    {value: 'The Aberdeenshire Council', label: 'The Aberdeenshire Council'},
  ];

  module.exports = ukLocalAuthorities;
